# Generated by Django 3.0.4 on 2020-03-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.CharField(default=0, max_length=400)),
                ('username', models.CharField(default=0, max_length=400)),
                ('status', models.CharField(default=0, max_length=400)),
                ('path', models.CharField(default=0, max_length=1000)),
                ('hierarchyName', models.CharField(default=0, max_length=400)),
            ],
        ),
    ]
