# Generated by Django 3.0.4 on 2020-03-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='files',
        ),
    ]
