# Generated by Django 3.0.4 on 2020-03-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_filesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='filesmodel',
            name='officeName',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='filesmodel',
            name='path',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='filesmodel',
            name='qr',
            field=models.CharField(max_length=400, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filesmodel',
            name='status',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='filesmodel',
            name='username',
            field=models.CharField(default='', max_length=400),
        ),
    ]
