# Generated by Django 3.0.4 on 2020-03-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20200327_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesmodel',
            name='path',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='filesmodel',
            name='status',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='filesmodel',
            name='username',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
