# Generated by Django 3.0.8 on 2020-07-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0003_auto_20200704_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='restrarted',
            new_name='restarted',
        ),
    ]
