# Generated by Django 3.0.8 on 2020-07-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0004_auto_20200704_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
