# Generated by Django 3.0.8 on 2020-07-04 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0005_auto_20200704_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='plan_to_send',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database_management.Role'),
        ),
    ]
