# Generated by Django 3.0.8 on 2020-08-15 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0006_auto_20200704_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='disapproved',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='file',
            name='plan_to_send_generator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_to_send_generator_person', to='database_management.AppUser'),
        ),
        migrations.AlterField(
            model_name='file',
            name='approved',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
