# Generated by Django 3.0.8 on 2020-08-19 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0009_auto_20200815_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='plan_to_send_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='plan_to_send_generator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_to_send_generator', to=settings.AUTH_USER_MODEL),
        ),
    ]
