# Generated by Django 3.0.8 on 2020-08-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0010_auto_20200819_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='plan_to_send_time',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
