# Generated by Django 3.0.8 on 2020-08-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0013_auto_20200819_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='plan_to_send_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
