# Generated by Django 3.0.4 on 2020-03-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveruser',
            name='hierarchyLevel',
            field=models.CharField(default='none', max_length=250, verbose_name='Hierarchy_Level'),
        ),
        migrations.AddField(
            model_name='driveruser',
            name='hierarchyName',
            field=models.CharField(default='none', max_length=250, verbose_name='Hierarchy_Name'),
        ),
    ]
