# Generated by Django 3.0.5 on 2020-04-08 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hierarchy_id', models.CharField(max_length=100, unique=True)),
                ('level', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('office_id', models.CharField(max_length=100, unique=True)),
                ('hierarchies', models.ManyToManyField(blank=True, to='databaseManagement.Hierarchy')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseManagement.Office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='databaseManagement.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.CharField(max_length=1000, unique=True)),
                ('current_level', models.CharField(default='Process is yet to begin', max_length=100)),
                ('path', models.CharField(default='User', max_length=1000)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('hierarchy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseManagement.Hierarchy')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseManagement.Office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='databaseManagement.UserAccount')),
            ],
        ),
    ]
