# Generated by Django 3.0.4 on 2020-03-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0002_auto_20200327_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hierarchymodel',
            old_name='category',
            new_name='office',
        ),
    ]
