# Generated by Django 3.0.4 on 2020-03-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0003_auto_20200327_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hierarchymodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='hierarchymodel',
            name='office',
            field=models.IntegerField(blank=True, default=0, primary_key=True, serialize=False),
        ),
    ]
