# Generated by Django 3.0.4 on 2020-03-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0004_auto_20200327_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchymodel',
            name='office',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
